server:
  port: 8080
spring:
  application:
    name: market-evaluation-gateway
  cloud:
    gateway:
      routes:
        - id: write-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/write/**
        - id: read-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/read/**
        - id: report-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/report/**